on:
  pull_request:

name: Unit tests
jobs:
  test_on_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.x
          cache: true

      - name: compile
        run: go build

      - name: run unit tests
        run: go test -v -tags=fast ./...

  test_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.x
          cache: true

      - name: compile
        run: go build

      - name: run unit tests
        run: go test -v -tags=fast ./...
